package main

import (
	"bytes"
	"encoding/binary"

	"github.com/karashiiro/ZanarkandWrapperJSON/sapphire"
)

// marshalType - Marshal an []byte to a packet structure
func marshalType(packetType string, data []byte) interface{} {
	generic := towerOfBabelSwitchEdition(packetType)

	buf := bytes.NewReader(data)
	binary.Read(buf, binary.LittleEndian, generic)

	return generic
}

// I call it this, but it's no VVVVV I guess
func towerOfBabelSwitchEdition(packetType string) interface{} {
	switch packetType {
	// ServerZoneDef.h
	case "Ping":
		return new(sapphire.Ping)
	case "Init":
		return new(sapphire.Init)
	case "Chat":
		return new(sapphire.Chat)
	case "ChatBanned":
		return new(sapphire.ChatBanned)
	case "WorldVisitList":
		return new(sapphire.WorldVisitList)
	case "Logout":
		return new(sapphire.Logout)
	case "PlayTime":
		return new(sapphire.PlayTime)
	case "PlayerEntry":
		return new(sapphire.PlayerEntry)
	case "SocialList":
		return new(sapphire.SocialList)
	case "ExamineSearchInfo":
		return new(sapphire.ExamineSearchInfo)
	case "SetSearchInfo":
		return new(sapphire.SetSearchInfo)
	case "InitSearchInfo":
		return new(sapphire.InitSearchInfo)
	case "ExamineSearchComment":
		return new(sapphire.ExamineSearchComment)
	case "ServerNoticeShort":
		return new(sapphire.ServerNoticeShort)
	case "ServerNotice":
		return new(sapphire.ServerNotice)
	case "SetOnlineStatus":
		return new(sapphire.SetOnlineStatus)
	case "BlackList":
		return new(sapphire.BlackList)
	case "LogMessage":
		return new(sapphire.LogMessage)
	case "LinkshellList":
		return new(sapphire.LinkshellList)
	case "ReqMoogleMailList":
		return new(sapphire.ReqMoogleMailList)
	case "MailLetterNotification":
		return new(sapphire.MailLetterNotification)
	case "FMarketTaxRates":
		return new(sapphire.MarketTaxRates)
	case "FMarketBoardItemListingCount":
		return new(sapphire.MarketBoardItemListingCount)
	case "MarketBoardItemListing":
		return new(sapphire.MarketBoardItemListing)
	case "MarketBoardItemListingHistory":
		return new(sapphire.MarketBoardItemListingHistory)
	case "MarketBoardSearchResult":
		return new(sapphire.MarketBoardSearchResult)
	case "ExamineFreeCompanyInfo":
		return new(sapphire.ExamineFreeCompanyInfo)
	case "FreeCompanyUpdateShortMessage":
		return new(sapphire.FreeCompanyUpdateShortMessage)
	case "StatusEffectList":
		return new(sapphire.StatusEffectList)
	case "FFXIVGCAffiliation":
		return new(sapphire.FFXIVGCAffiliation)
	case "EffectResult":
		return new(sapphire.EffectResult)
	case "ActorControl":
		return new(sapphire.ActorControl)
	case "ActorControlSelf":
		return new(sapphire.ActorControlSelf)
	case "ActorControlTarget":
		return new(sapphire.ActorControlTarget)
	case "UpdateHpMpTp":
		return new(sapphire.UpdateHpMpTp)
	case "Effect":
		return new(sapphire.Effect)
	case "AoeEffect8":
		return new(sapphire.AoeEffect8)
	case "AoeEffect16":
		return new(sapphire.AoeEffect16)
	case "AoeEffect24":
		return new(sapphire.AoeEffect24)
	case "AoeEffect32":
		return new(sapphire.AoeEffect32)
	case "PlayerSpawn":
		return new(sapphire.PlayerSpawn)
	case "NpcSpawn":
		return new(sapphire.NpcSpawn)
	case "ActorFreeSpawn":
		return new(sapphire.ActorFreeSpawn)
	case "ActorMove":
		return new(sapphire.ActorMove)
	case "ActorSetPos":
		return new(sapphire.ActorSetPos)
	case "ActorCast":
		return new(sapphire.ActorCast)
	case "HateList":
		return new(sapphire.HateList)
	case "HateRank":
		return new(sapphire.HateRank)
	case "UpdateClassInfo":
		return new(sapphire.UpdateClassInfo)
	case "PlayerTitleList":
		return new(sapphire.PlayerTitleList)
	case "InitZone":
		return new(sapphire.InitZone)
	case "PlayerSetup":
		return new(sapphire.PlayerSetup)
	case "PlayerStats":
		return new(sapphire.PlayerStats)
	case "ActorOwner":
		return new(sapphire.ActorOwner)
	case "PlayerStateFlags":
		return new(sapphire.PlayerStateFlags)
	case "PlayerClassInfo":
		return new(sapphire.PlayerClassInfo)
	case "ModelEquip":
		return new(sapphire.ModelEquip)
	case "Examine":
		return new(sapphire.Examine)
	case "CharaNameReq":
		return new(sapphire.CharaNameReq)
	case "ItemInfo":
		return new(sapphire.ItemInfo)
	case "ContainerInfo":
		return new(sapphire.ContainerInfo)
	case "CurrencyCrystalInfo":
		return new(sapphire.CurrencyCrystalInfo)
	case "InventoryTransactionFinish":
		return new(sapphire.InventoryTransactionFinish)
	case "InventoryTransaction":
		return new(sapphire.InventoryTransaction)
	case "InventoryActionAck":
		return new(sapphire.InventoryActionAck)
	case "UpdateInventorySlot":
		return new(sapphire.UpdateInventorySlot)
	case "EventStart":
		return new(sapphire.EventStart)
	case "HuntingLogEntry":
		return new(sapphire.HuntingLogEntry)
	case "EventPlay":
		return new(sapphire.EventPlay)
	case "EventPlay4":
		return new(sapphire.EventPlay4)
	case "EventPlay8":
		return new(sapphire.EventPlay8)
	case "EventPlay16":
		return new(sapphire.EventPlay16)
	case "EventPlay32":
		return new(sapphire.DirectorPlayScene)
	case "EventPlay64":
		return new(sapphire.EventPlay64)
	case "EventPlay128":
		return new(sapphire.EventPlay128)
	case "EventFinish":
		return new(sapphire.EventFinish)
	case "EventPlay255":
		return new(sapphire.EventPlay255)
	case "EventLinkshell":
		return new(sapphire.EventLinkshell)
	case "QuestActiveList":
		return new(sapphire.QuestActiveList)
	case "QuestUpdate":
		return new(sapphire.QuestUpdate)
	case "QuestCompleteList":
		return new(sapphire.QuestCompleteList)
	case "QuestFinish":
		return new(sapphire.QuestFinish)
	case "QuestMessage":
		return new(sapphire.QuestMessage)
	case "QuestTracker":
		return new(sapphire.QuestTracker)
	case "WeatherChange":
		return new(sapphire.WeatherChange)
	case "Discovery":
		return new(sapphire.Discovery)
	case "FFXIVARR_IPC_UNK322":
		return new(sapphire.FFXIVARR_IPC_UNK322)
	case "FFXIVARR_IPC_UNK320":
		return new(sapphire.FFXIVARR_IPC_UNK320)
	case "PrepareZoning":
		return new(sapphire.PrepareZoning)
	case "CFNotify":
		return new(sapphire.CFNotify)
	case "CFAvailableContents":
		return new(sapphire.CFAvailableContents)
	case "CFPlayerInNeed":
		return new(sapphire.CFPlayerInNeed)
	case "CFDutyInfo":
		return new(sapphire.CFDutyInfo)
	case "CFRegisterDuty":
		return new(sapphire.CFRegisterDuty)
	case "CFMemberStatus":
		return new(sapphire.CFMemberStatus)
	case "EorzeaTimeOffset":
		return new(sapphire.EorzeaTimeOffset)
	case "EquipDisplayFlags":
		return new(sapphire.EquipDisplayFlags)
	case "Mount":
		return new(sapphire.Mount)
	case "DirectorVars":
		return new(sapphire.DirectorVars)
	case "DirectorPopUp":
		return new(sapphire.DirectorPopUp)
	case "ActorGauge":
		return new(sapphire.ActorGauge)
	case "PerformNote":
		return new(sapphire.PerformNote)
	case "HousingUpdateLandFlagsSlot":
		return new(sapphire.HousingUpdateLandFlagsSlot)
	case "HousingLandFlags":
		return new(sapphire.HousingLandFlags)
	case "LandStruct":
		return new(sapphire.LandStruct)
	case "LandUpdate":
		return new(sapphire.LandUpdate)
	case "LandPriceUpdate":
		return new(sapphire.LandPriceUpdate)
	case "LandInfoSign":
		return new(sapphire.LandInfoSign)
	case "LandRename":
		return new(sapphire.LandRename)
	case "LandUpdateHouseName":
		return new(sapphire.LandUpdateHouseName)
	case "LandSetMap":
		return new(sapphire.LandSetMap)
	case "LandSetInitialize":
		return new(sapphire.LandSetInitialize)
	case "YardObjectSpawn":
		return new(sapphire.YardObjectSpawn)
	case "HousingObjectMove":
		return new(sapphire.HousingObjectMove)
	case "HousingObjectInitialize":
		return new(sapphire.HousingObjectInitialize)
	case "HousingInternalObjectSpawn":
		return new(sapphire.HousingInternalObjectSpawn)
	case "HousingIndoorInitialize":
		return new(sapphire.HousingIndoorInitialize)
	case "HousingWardInfo":
		return new(sapphire.HousingWardInfo)
	case "HousingEstateGreeting":
		return new(sapphire.HousingEstateGreeting)
	case "HousingShowEstateGuestAccess":
		return new(sapphire.HousingShowEstateGuestAccess)
	case "SharedEstateSettingsResponse":
		return new(sapphire.SharedEstateSettingsResponse)
	case "MSQTrackerProgress":
		return new(sapphire.MSQTrackerProgress)
	case "MSQTrackerComplete":
		return new(sapphire.MSQTrackerComplete)
	case "ObjectSpawn":
		return new(sapphire.ObjectSpawn)
	case "ObjectDespawn":
		return new(sapphire.ObjectDespawn)
	case "DuelChallenge":
		return new(sapphire.DuelChallenge)
	case "RetainerInformation":
		return new(sapphire.RetainerInformation)
	// ClientZoneDef.h
	case "GmCommand1":
		return new(sapphire.GmCommand1)
	case "GmCommand2":
		return new(sapphire.GmCommand2)
	case "ClientTrigger":
		return new(sapphire.ClientTrigger)
	case "UpdatePosition":
		return new(sapphire.UpdatePosition)
	case "SkillHandler":
		return new(sapphire.SkillHandler)
	case "AoESkillHandler":
		return new(sapphire.AoESkillHandler)
	case "ZoneLineHandler":
		return new(sapphire.ZoneLineHandler)
	case "DiscoveryHandler":
		return new(sapphire.DiscoveryHandler)
	case "EventHandlerReturn":
		return new(sapphire.EventHandlerReturn)
	case "EnterTerritoryHandler":
		return new(sapphire.EnterTerritoryHandler)
	case "EventHandlerOutsideRange":
		return new(sapphire.EventHandlerOutsideRange)
	case "EventHandlerWithinRange":
		return new(sapphire.EventHandlerWithinRange)
	case "EventHandlerEmote":
		return new(sapphire.EventHandlerEmote)
	case "EventHandlerTalk":
		return new(sapphire.EventHandlerTalk)
	case "PingHandler":
		return new(sapphire.PingHandler)
	case "SetSearchInfoHandler":
		return new(sapphire.SetSearchInfoHandler)
	case "TellHandler":
		return new(sapphire.TellHandler)
	case "ChatHandler":
		return new(sapphire.ChatHandler)
	case "ShopEventHandler":
		return new(sapphire.ShopEventHandler)
	case "LinkshellEventHandler":
		return new(sapphire.LinkshellEventHandler)
	case "InventoryModifyHandler":
		return new(sapphire.InventoryModifyHandler)
	case "RenameLandHandler":
		return new(sapphire.RenameLandHandler)
	case "HousingUpdateHouseGreeting":
		return new(sapphire.HousingUpdateHouseGreeting)
	case "BuildPresetHandler":
		return new(sapphire.BuildPresetHandler)
	case "SetSharedEstateSettings":
		return new(sapphire.SetSharedEstateSettings)
	case "MarketBoardRequestItemListings":
		return new(sapphire.MarketBoardRequestItemListings)
	case "ReqPlaceHousingItem":
		return new(sapphire.ReqPlaceHousingItem)
	case "HousingUpdateObjectPosition":
		return new(sapphire.HousingUpdateObjectPosition)
	case "MarketBoardSearch":
		return new(sapphire.MarketBoardSearch)
	case "MarketBoardRequestItemListingInfo":
		return new(sapphire.MarketBoardRequestItemListingInfo)
	case "FreeCompanyUpdateShortMessageHandler":
		return new(sapphire.FreeCompanyUpdateShortMessageHandler)
	// ServerLobbyDef.h
	case "RetainerList":
		return new(sapphire.RetainerList)
	case "ServiceIdInfo":
		return new(sapphire.ServiceIdInfo)
	case "ServerList":
		return new(sapphire.ServerList)
	case "CharList":
		return new(sapphire.CharList)
	case "EnterWorld":
		return new(sapphire.EnterWorld)
	case "CharCreate":
		return new(sapphire.CharCreate)
	case "LobbyError":
		return new(sapphire.LobbyError)
	// ClientChatDef.h
	case "Tell":
		return new(sapphire.Tell)
	case "TellErrNotFound":
		return new(sapphire.TellErrNotFound)
	case "FreeCompanyEvent":
		return new(sapphire.FreeCompanyEvent)
	}

	return new(interface{})
}
