name: Go

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create a Release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name: v${{ github.run_id }}
          # The name of the release. For example, `Release v1.0.1`
          release_name: v${{ github.run_id }}
